"""initial_schema

Revision ID: 8c60af17e0c5
Revises: 
Create Date: 2026-03-20 19:16:54.602406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c60af17e0c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recordings', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('recordings', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.alter_column('recordings', 'sentence_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.create_index(op.f('ix_recordings_sentence_id'), 'recordings', ['sentence_id'], unique=False)
    op.create_index(op.f('ix_recordings_status'), 'recordings', ['status'], unique=False)
    op.create_index(op.f('ix_recordings_user_id'), 'recordings', ['user_id'], unique=False)
    op.create_unique_constraint('uq_recording_user_sentence', 'recordings', ['user_id', 'sentence_id'])
    op.alter_column('sentences', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.create_index(op.f('ix_sentences_status'), 'sentences', ['status'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sentences_status'), table_name='sentences')
    op.alter_column('sentences', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint('uq_recording_user_sentence', 'recordings', type_='unique')
    op.drop_index(op.f('ix_recordings_user_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_status'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_sentence_id'), table_name='recordings')
    op.alter_column('recordings', 'sentence_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('recordings', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('recordings', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
